services:
  helsinki-nlp:
    build: ./hugging_face
    volumes:
      - ./hugging_face:/app
      - ./data_files:/app/data_files
      - ./transformers_models:/root/.cache/huggingface
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  django:
    build:
      context: ./django
    volumes:
      - ./django:/app
      - ./data_files:/app/data_files
    ports:
      - "8000:8000"
    depends_on:
      - helsinki-nlp
    command: python manage.py runserver 0.0.0.0:8000
